name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Test contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Compile tests
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test
